# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'

name: $(Major).$(Minor)$(Rev:.r)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test test/AisParserTests --configuration $(buildConfiguration) --logger trx
  displayName: Run tests

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet pack -c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -p:PackageVersion=$(Build.BuildNumber)
  displayName: NuGet pack

- task: PublishBuildArtifacts@1
