name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup dotnet 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.201'
    - name: Build and Test
      run: ./build.ps1
      shell: pwsh
    - name: Push to MyGet
      env:
        NUGET_URL: https://www.myget.org/F/aisparser/api/v3/index.json
        NUGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
      run: ./release.ps1
      shell: pwsh
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/**/*